function aihelper {
  param(
    [string]\ = "ollama/qwen2.5-coder:7b",
    [switch]\,
    [switch]\
  )
  \Continue = "Stop"
  \C:\Users\posan\OneDrive\Desktop\AI HELPER = "C:\Users\posan\OneDrive\Desktop\AI HELPER"
  \http://127.0.0.1:11435 = "http://127.0.0.1:11435"

  # 1) Point Aider to your Ollama server each time
  \http://127.0.0.1:11435 = \http://127.0.0.1:11435

  # 2) Check Ollama is up
  try {
    Write-Host "🔍 Checking Ollama at \http://127.0.0.1:11435 ..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri "\http://127.0.0.1:11435/api/version" -UseBasicParsing -TimeoutSec 3 | Out-Null
  } catch {
    Write-Host "⚠️  Ollama isn't responding on \http://127.0.0.1:11435. Open the Ollama app, then run: aihelper" -ForegroundColor Yellow
    return
  }
  Write-Host "✅ Ollama OK" -ForegroundColor Green

  # 3) Ensure project folder exists and has a sane config
  if (!(Test-Path \C:\Users\posan\OneDrive\Desktop\AI HELPER)) { New-Item -Type Directory \C:\Users\posan\OneDrive\Desktop\AI HELPER | Out-Null }
  Set-Location \C:\Users\posan\OneDrive\Desktop\AI HELPER

  if (!(Test-Path ".aider.conf.yml")) {
    @"
model: \
edit_format: diff
auto_commits: true
git: true
system_message: |
  You are a senior engineer working in this repo.
  - Minimal, correct diffs; keep changes atomic.
  - Python: PEP8, type hints, docstrings; add/adjust tests.
  - Explain intent in commit messages.
