"""add_user_model

Revision ID: 79b662da8d66
Revises: 20251003_01
Create Date: 2025-10-04 22:44:45.345833

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b662da8d66'
down_revision = '20251003_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.drop_constraint(op.f('news_articles_source_id_fkey'), 'news_articles', type_='foreignkey')
        op.create_foreign_key(
            op.f('news_articles_source_id_fkey'),
            'news_articles',
            'news_sources',
            ['source_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.drop_constraint(op.f('news_articles_source_id_fkey'), 'news_articles', type_='foreignkey')
        op.create_foreign_key(
            op.f('news_articles_source_id_fkey'),
            'news_articles',
            'news_sources',
            ['source_id'],
            ['id'],
            ondelete='CASCADE',
        )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
